(coq.theory
 (name Waterproof)
 (package rocq-waterproof)
 (flags :standard)
 (theories Stdlib Ltac2)
 (plugins rocq-waterproof.plugin rocq-runtime.plugins.ltac rocq-runtime.plugins.ltac2))

(include_subdirs qualified)

(rule
 (alias runtest)
 (deps
  (package rocq-waterproof)
  (package rocq-lsp)
  %{project_root}/tests/test-folder.py
  (source_tree %{workspace_root}/test-exercises))
 (action (progn
             (echo "Testing:")
             (run pwd)
             (run python3 %{project_root}/tests/test-folder.py %{workspace_root}/../../test-exercises/)
)))
