name: Build with make

on: [push, workflow_dispatch]

concurrency:
  group: "build-with-make"
  cancel-in-progress: true

jobs:

  build:
    name: build with make
    runs-on: ubuntu-latest
    container:
      image: coqorg/coq:8.17-ocaml-4.14-flambda
      options: --user root

    steps:
      - name: Set up git repository
        uses: actions/checkout@v3
      
      - name: Build plugin with make
        run: |
            chmod -R 777 ./
            CURRENT_DIRECTORY=$(pwd)
            echo "Current directory: $CURRENT_DIRECTORY"
            su - coq -c "cd $CURRENT_DIRECTORY && pwd && make"
            su - coq -c "cd $CURRENT_DIRECTORY && pwd && make install"
