name: Create docker export for WSL distro

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: Create docker export for WSL distro
    runs-on: ubuntu-latest

    steps:
      - name: Set up git repository
        uses: actions/checkout@v3

      - name: Echo github workspace variables
        run: | 
          echo $GITHUB_WORKSPACE
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo $GITHUB_REF_NAME

      - name: Create file that can be imported by WSL
        run: |
          docker build --build-arg SOURCE=$GITHUB_SHA --build-arg BRANCH=$GITHUB_REF_NAME -t waterproof-image:tmp .
          docker run -d -it --name waterproof-container waterproof-image:tmp
          docker export --output="/tmp/ubuntu-waterproof.tar" waterproof-container
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-waterproof
          path: /tmp/ubuntu-waterproof.tar